### PR TITLE
Fixes Fahrenheit missing conversion for JSON and RAW output modes

### PR DESCRIPTION
**Pull request by HorlogeSkynet**
Hey there !

Back in 2017 when the `-j` option has been added (1b36ea429930b05e1b3cb77cdbc24cb1ffbcac61), the Fahrenheit conversion has not been implemented.
This quick-and-dirty patch fixes this behavior, making both `-j` and `-f` options _compatible_.
It has been tested on my own Debian system.

Bye :wave:

EDIT : New commit added afterwards relative to the `-u` (raw output) flag.

### CODE REVIEW

**Comment by HorlogeSkynet** [comment]
Hey there, little up ! Bye 👋

**Comment by olysonek** [comment]
Hi. Thanks for the ping and sorry for the delay. Can you change the commit message of the second commit to something like the following, instead of linking to the other commit?
"Fix missing Fahrenheit conversion with raw output enabled"

I'll merge it after that.

**Comment by HorlogeSkynet** [comment]
No problem @olysonek, here you go. Bye 👋

**Comment by olysonek** [comment]
Great, thanks!

**Pull request merged**
