### PR TITLE
configs: Add entry for GA-AB350N-Gaming WIFI (rev. 1.0)

### PR DESCRIPTION
**Pull request by konomikitten**
I've not written configs for lm-sensors before so input is welcome. I used the manual and images provided by the manufacture to write this config along with a large amount of screenshots from HWiNFO64 from Windows.

### CODE REVIEW

**Comment by olysonek** [comment]
It looks good to me. Thanks!

**Comment by leighbb** [comment]
It would be good to add the DMI information for this board, e.g.:

# dmi: board_name:   <from dmidecode>
# dmi: board_vendor: <from dmidecode>
# dmi: bios_version: <from dmidecode>

**Comment by olysonek** [comment]
Yes, that's a good suggestion. @konomikitten Feel free to do another PR :).

**Comment by konomikitten** [comment]
I've done a new pull request with the information needed, #247.

**Comment by olysonek** [comment]
#248

**Pull request merged**
