### PR TITLE
Update GA-AB350N-GAMING-WIFI-REV1.0.conf

### PR DESCRIPTION
**Pull request by konomikitten**
Add /sys/devices/virtual/dmi/id fields.

### CODE REVIEW

**Comment by olysonek** [comment]
Please use a more specific summary in the commit message, e.g. "Add DMI information to GA-AB350N-GAMING-WIFI-REV1.0.conf"

**Comment by konomikitten** [comment]
@olysonek hi, I've not made many pull requests before on GitHub, am I able to edit the commit message or do I need to submit a new pull request?

**Comment by olysonek** [comment]
I don't know what your setup is, but normally you would `cd` into the lm_sensors repository, run `git commit --amend` to change the commit message of the last commit and the push the changes to Github using `git push --force`. Does that help?

**Comment by konomikitten** [comment]
That just seems to have made more of a mess, I'm going to close this pull request and make a fresh one.

**Pull request closed without merging**
