### PR TITLE
add Gigabyte GA-F2A88XM-HD3 and MSI MS-7A34 (B350 TOMAHAWK) config

### PR DESCRIPTION
**Pull request by maciejsszmigiero**
This pull request adds configs for Gigabyte GA-F2A88XM-HD3 and MSI MS-7A34 (B350 TOMAHAWK)
boards.

Input routings and scalings were read from schematic of either the board itself
(in the GA-F2A88XM-HD3 case) or from a similar board (in the MSI MS-7A34 case),
then confirmed experimentally.

### CODE REVIEW

**Comment by maciejsszmigiero** [comment]
Ping.

**Comment by olysonek** [comment]
Sorry for the delay. It would be nice if you could add brief comments to the configs that justify ignoring the voltage and temperature inputs ("stuck at 0" etc.).

Also, the config files usually state the name and email of the author in the header. Add that, if you're comfortable with it.

Thanks.

**Comment by olysonek** [comment]
Other than that, this looks good to me.

**Comment by maciejsszmigiero** [comment]
Thanks for looking at it.

I have now updated these configs with authorship headers and also with
the remaining descriptions of ignored temperature and voltage inputs.

**Comment by olysonek** [comment]
Thanks, merged.

**Pull request merged**
