### PR TITLE
configs: Add MSI B450M Mortar board

### PR DESCRIPTION
**Pull request by hannesha**
Tested on a B450M Mortar Titanium board, but it shares the same ID with the B450M Mortar board.

### CODE REVIEW

**Comment by olysonek** [comment]
> Tested on a B450M Mortar Titanium board, but it shares the same ID with the B450M Mortar board.

OK. Please put that information in a comment to the top of the file. Other than that, this looks good to me. Thank you!

**Comment by hannesha** [comment]
Ok, I added this information to the header comments.

**Comment by olysonek** [comment]
Thanks!

**Comment by Spazumn** [comment]
Hello everybody on this thread
How would myself, go about re coding, testing the script for an similar, (Not exact) motherboard?
 
My  board is a MSI B450M PRO VDH MAX.

I do not want to commit plagiarism, but at the same time request, to rewrite code that will work with my motherboard; without having to reinvent the wheel.

Please suggest, comment, criticize freely would be appreciated.
I'm not afraid of high technical computer talk. Throw me the engineering specs, and low level bit, bytes.
I am fluent in MSDOS, some LINUX script and have authored some QBASIC, VIisual BASIC (before .NET versions)
Old schooled in Pascal, COBOL on a non professional level. I worked at a computer factory testing ruggedized PC units that are plugged into military troop carrier vehicles. 
I also built this Gamer Rig, installed Windows and Linux dual boot. 

Thanks

**Pull request merged**
