### PR TITLE
configs: Add ASUS PRIME Z370-A motherboard

### PR DESCRIPTION
**Pull request by jonasmalacofilho**
Tested with i7-8700K and two UEFI versions.

### CODE REVIEW

**Comment by Leo-PL** [comment]
Will have to test it out at work, I have this exact mobo in CPU there.
Thanks!

**Comment by newAM** [comment]
Works for me, thanks!

```
"description" : "Motherboard",
"product" : "PRIME Z370-A",
"vendor" : "ASUSTeK COMPUTER INC.",
"version" : "1601",
"date" : "10/29/2018",
```

**Comment by DragoonX6** [comment]
Confirmed working for me too!

**Comment by olysonek** [comment]
Very nicely documented, thanks!

**Pull request merged**
