### PR TITLE
configs: add support for X470 ultra gaming (WIP)

### PR DESCRIPTION
**Pull request by karolgrudzinski**
Initial config for Gigabyte X470 AORUS ULTRA GAMING
https://www.gigabyte.com/Motherboard/X470-AORUS-ULTRA-GAMING-rev-10
   
This config is based on:
      - GA-AB350-GAMING3.conf
      - GA-AX370-GAMING5.conf
      - output of HWiNFO64 Sensor Status program on Windows

### CODE REVIEW

**Comment by terencode** [comment]
Hey, is this still a work-in-progress?

**Comment by karolgrudzinski** [comment]
I don't know if it can be considered a work in progress. I made this config file for my personal PC, I use it for about a year. I personally care only about temperature and fans rpm readings. I don't really care about voltages because I don't do overclocking so I don't know if it reports correct values because of zero feedback for this PR.
If there is still any interest I will rebase my outdated branch onto current master.

**Comment by terencode** [comment]
I use it since 3 months. The voltages look OK to me except the vcore from it8792-isa-0a60 which always reports +1.80 V

**Comment by karolgrudzinski** [comment]
I get that on my pc:

```
it8792-isa-0a60
Adapter: ISA adapter
CPU Vcore:      +0.81 V  (min =  +0.00 V, max =  +2.78 V)
DDR VTT:        +0.68 V  (min =  +0.00 V, max =  +2.78 V)
Chipset Core:   +1.06 V  (min =  +0.00 V, max =  +2.78 V)
+3.3V:          +3.36 V  (min =  +0.00 V, max =  +5.56 V)
CPU Vdd18:      +1.78 V  (min =  +0.00 V, max =  +2.78 V)
DDR Vpp A/B:    +2.50 V  (min =  +0.00 V, max =  +4.63 V)
in6:            +2.78 V  (min =  +0.00 V, max =  +2.78 V)  ALARM
3VSB:           +3.33 V  (min =  +0.00 V, max =  +5.56 V)
Vbat:           +3.14 V  
SYS_FAN5_PUMP: 1069 RPM  (min =    0 RPM)
SYS_FAN6_PUMP:    0 RPM  (min =    0 RPM)
SYS_FAN4:      1090 RPM  (min =    0 RPM)
PCIEX8:         +36.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
EC_TEMP:        +28.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
System 2:       +35.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
intrusion0:    ALARM

k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +35.4°C  (high = +70.0°C)
Tctl:         +35.4°C  

it8686-isa-0a40
Adapter: ISA adapter
CPU Vcore:      +0.82 V  (min =  +0.00 V, max =  +3.06 V)
+3.3V:          +3.27 V  (min =  +0.00 V, max =  +5.05 V)
+12V:          +12.17 V  (min =  +0.00 V, max = +18.36 V)
+5V:            +4.98 V  (min =  +0.00 V, max =  +7.65 V)
CPU Vcore SOC:  +0.94 V  (min =  +0.00 V, max =  +3.06 V)
CPU Vddp:       +0.91 V  (min =  +0.00 V, max =  +3.06 V)
DRAM A/B:       +1.38 V  (min =  +0.00 V, max =  +3.06 V)
3VSB:           +3.26 V  (min =  +0.00 V, max =  +6.12 V)
Vbat:           +3.05 V  
CPU_FAN:       1147 RPM  (min =    0 RPM)
SYS_FAN1:       932 RPM  (min =    0 RPM)
SYS_FAN2:         0 RPM  (min =    0 RPM)
SYS_FAN3:         0 RPM  (min =    0 RPM)
CPU_OPT:          0 RPM  (min =    0 RPM)
System 1:       +33.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
Chipset:        +41.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
CPU Socket:     +35.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = AMD AMDSI
PCIEX16:        +35.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
VRM MOS:        +42.0°C  (low  =  +0.0°C, high = -118.0°C)  sensor = thermistor
VSOC MOS:       +45.0°C  (low  =  +0.0°C, high = -118.0°C)  sensor = thermistor
intrusion0:    ALARM
```

It needs some work e.g. min and max values.

**Comment by terencode** [comment]
I'd be happy to help but I don't know how to compare to the actual values

**Comment by olysonek** [comment]
This looks good to me. Thanks.

**Pull request merged**
