### PR TITLE
libsensors: Fix support for driver names with dashes

### PR DESCRIPTION
**Pull request by albard00**
The dash is used as delimiter in the conversion rules. This works fine
with kernel drivers with simple names like lm75, but some drivers have a
compound name like da9063-hwmon which were not handled properly by these
rules.

### CODE REVIEW

**Comment by Wer-Wolf** [comment]
This would be a kernel bug, since hwmon chip names are forbidden to contain such characters.
Can you show me the output of `lsmod`, so i can identify the offending kernel driver?

**Comment by albard00** [comment]
~~The drivers is da9063-hwmon~~ This driver is actually not mainline. That's probably the problem then.

**Comment by albard00** [comment]
It is using the deprecated function hwmon_device_register.
But somehow there is still something strange: it is reported with this ambiguous name which cannot be used in the rules :

\# sensors -u
da9063-hwmon-isa-0000
Adapter: ISA adapter
VSYS:
  in0_input: 4.611
ADCIN1:
  in1_input: 1.596
ADCIN2:
  in2_input: 2.500
ADCIN3:
  in3_input: 2.500
VBBAT:
  in4_input: 4.379
TJUNC:
  temp1_input: 62.678

**Comment by Wer-Wolf** [comment]
da9063-hwmon is the chip name, -isa-0000
is added by libsensors itself.

I think the solution would be to update this kernel module to using hwmon_device_register_with_info.

**Comment by albard00** [comment]
Yep, I will go this way. Thanks for your support.

**Comment by Wer-Wolf** [comment]
Just a question: is this driver out of tree?

**Comment by albard00** [comment]
No it is in-tree and built-in

**Comment by Wer-Wolf** [comment]
Can you tell me the filename?

**Comment by albard00** [comment]
the filename is da9063-hwmon.c. but it is not mainline, it is part of our modified kernel sources.

**Comment by Wer-Wolf** [comment]
You should try to upstream it then.
Such an error would have been easily discovered and fixed.
Some tried this already, see [here](https://lore.kernel.org/lkml/2c24ef5953401e80d92c907704bffeff1d024de0.1625662290.git.plr.vincent@gmail.com/)

**Pull request closed without merging**
