### PR TITLE
Add support for Nuvoton NCT6112D/NCT6114D/NCT6116D Super IO Sensors

### PR DESCRIPTION
**Pull request by luca020400**

### CODE REVIEW

**Comment by luca020400** [comment]
Untested but this brings nct6775 detection inline with hwmon-next
See https://git.kernel.org/pub/scm/linux/kernel/git/groeck/linux-staging.git/commit?h=hwmon-next&id=dbadea52204da2fd4974c49bf3ca55461df906ba

**Comment by olysonek** [comment]
Thanks, looks good to me. I was waiting for this to get to the mainline, so that I can reference the final commit hash. The thing is that hwmon-next sometimes rebases and I'm not sure if the dbadea52204da2fd4 commit will remain in existence. But it would be nice to have a better workflow than to wait for things to reach mainline.

@groeck When do you rebase hwmon-next? Is it safe to assume that it won't rebase until it's merged to the mainline when the next merge window opens?

**Comment by luca020400** [comment]
Even if the change get rebased, the link would still work even if it isn't present in any branch.
But I agree we can wait, just made sure everyone can enjoy their hw :)

**Comment by olysonek** [comment]
Are you sure it won't get garbage-collected? I don't trust it :).

**Comment by luca020400** [comment]
I would hope such development trees to never be gc'd
But once again, I don't know :)

**Comment by groeck** [comment]
hwmon and hwmon-next are working branches and may be rebased at any time. Commit SHAs into either of those branches are not considered stable.
At the same time, I don't see the point in holding up any patches into lm-sensors because of the workflow of hwmon-next, nor the need to reference kernel SHAs in lm-sensors in the first place. After all, the important information is that support for NCT611X will be available in v5.4, not its commit SHA. If the commit SHA is important for you, you'll have to wait for the next kernel release.

**Comment by olysonek** [comment]
I consider kernel commits potentially valuable reference information. Being able to lookup the exact kernel patches that the lm_sensors patches were based on makes it much easier to see why the patches are the way they are.

Let's link to patchwork. @luca020400 can you add this link to the commit message?
https://patchwork.kernel.org/patch/11044521/#22774197

**Comment by luca020400** [comment]
Sure I can

**Comment by luca020400** [comment]
Done

**Comment by olysonek** [comment]
Thanks!

**Comment by luca020400** [comment]
You're welcome!

**Comment by luca020400** [comment]
@groeck Sorry for the OT, but are any plans to backport the new ryzen k10temp support to stable/5.3?
It's just 2 patches and 5 line additions in total

**Comment by groeck** [comment]
Not sure what this has to do with this pull request. Anyway, the k10temp patches touch two subsystems, the x86 maintainers are quite picky when it comes to patches into x86, and I did not get permission from a x86 maintainer to apply the patches to stable releases. Please feel free to make this request in response to the patches. If there is a reply, I'll be happy to do it.

**Pull request merged**
